=== adoptium/TKG/resources/playlist.xsd
<?xml version="1.0" encoding="UTF-8" ?>

<!--
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
-->

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="playlist">
    <xs:complexType>
      <xs:sequence>
        <xs:element type="xs:string" name="include" minOccurs="0"/>
        <xs:element name="test" maxOccurs="unbounded" minOccurs="1">
          <xs:complexType>
            <xs:all>
              <xs:element name="disables" maxOccurs="1" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="disable" maxOccurs="unbounded" minOccurs="1">
                      <xs:complexType>
                        <xs:all>
                          <xs:element type="xs:string" name="comment" maxOccurs="1" minOccurs="1"/>
                          <xs:element type="xs:string" name="variation" maxOccurs="1" minOccurs="0"/>
                          <xs:element type="xs:string" name="version" maxOccurs="1" minOccurs="0"/>
                          <xs:element type="xs:string" name="impl" maxOccurs="1" minOccurs="0"/>
                          <xs:element type="xs:string" name="vendor" maxOccurs="1" minOccurs="0"/>
                          <xs:element type="xs:string" name="platform" maxOccurs="1" minOccurs="0"/>
                          <xs:element type="xs:string" name="testflag" maxOccurs="1" minOccurs="0"/>
                        </xs:all>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element type="xs:string" name="testCaseName" maxOccurs="1" minOccurs="1"/>
              <xs:element name="variations" maxOccurs="1" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="variation" maxOccurs="unbounded" minOccurs="1"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element type="xs:string" name="command" maxOccurs="1" minOccurs="1"/>
              <xs:element type="xs:string" name="capabilities" maxOccurs="1" minOccurs="0"/>
              <xs:element type="xs:string" name="platformRequirements" maxOccurs="1" minOccurs="0"/>
              <xs:element type="xs:string" name="platform" maxOccurs="1" minOccurs="0"/>
              <xs:element type="xs:string" name="aot" maxOccurs="1" minOccurs="0"/>
              <xs:element name="levels" maxOccurs="1" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="level" maxOccurs="unbounded" minOccurs="1"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="groups" maxOccurs="1" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="group" maxOccurs="unbounded" minOccurs="1"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="types" maxOccurs="1" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="type" maxOccurs="unbounded" minOccurs="1"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="impls" maxOccurs="1" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="impl" maxOccurs="unbounded" minOccurs="1"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="vendors" maxOccurs="1" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="vendor" maxOccurs="unbounded" minOccurs="1"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="versions" maxOccurs="1" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="version" maxOccurs="unbounded" minOccurs="1"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:all>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== adoptium/TKG/examples/sliceAndDice/level/playlist.xml
<?xml version='1.0' encoding='UTF-8'?>
<!--
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
-->
<playlist xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../resources/playlist.xsd">
	<test>
		<testCaseName>testDefault</testCaseName>
		<command>echo "default is extended"; \
	$(TEST_STATUS)</command>
	</test>

	<test>
		<testCaseName>testSanity</testCaseName>
		<command>echo "sanity"; \
	$(TEST_STATUS)</command>
		<levels>
			<level>sanity</level>
		</levels>
	</test>

	<test>
		<testCaseName>testExtended</testCaseName>
		<command>echo "extended"; \
	$(TEST_STATUS)</command>
		<levels>
			<level>extended</level>
		</levels>
	</test>

	<test>
		<testCaseName>testDev</testCaseName>
		<command>echo "dev"; \
	$(TEST_STATUS)</command>
		<levels>
			<level>dev</level>
		</levels>
	</test>

	<test>
		<testCaseName>testSpecial</testCaseName>
		<command>echo "special"; \
	$(TEST_STATUS)</command>
		<levels>
			<level>special</level>
		</levels>
	</test>
</playlist>

=== adoptium/TKG/examples/jdkVersion/playlist.xml
<?xml version='1.0' encoding='UTF-8'?>
<!--
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
-->
<playlist xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../resources/playlist.xsd">
	<test>
		<testCaseName>test_ver_11</testCaseName>
		<command>echo "test for version 11"; \
	$(TEST_STATUS)</command>
		<versions>
			<version>11</version>
		</versions>
	</test>

	<test>
		<testCaseName>test_ver_17plus</testCaseName>
		<command>echo "test for version 17+"; \
	$(TEST_STATUS)</command>
		<versions>
			<version>17+</version>
		</versions>
	</test>

	<test>
		<testCaseName>test_ver_8to11</testCaseName>
		<command>echo "test for version 8 to 11"; \
	$(TEST_STATUS)</command>
		<versions>
			<version>[8, 11]</version>
		</versions>
	</test>

	<test>
		<testCaseName>test_ver_8to11and17plus</testCaseName>
		<command>echo "test for version 8 to 11 and 17+"; \
	$(TEST_STATUS)</command>
		<versions>
			<version>[8, 11]</version>
			<version>17+</version>
		</versions>
	</test>

	<test>
		<testCaseName>test_disable_ver_11</testCaseName>
		<disables>
			<disable>
				<comment>disable version 11</comment>
				<version>11</version>
			</disable>
		</disables>
		<command>echo "disable test for version 11"; \
	$(TEST_STATUS)</command>
	</test>

	<test>
		<testCaseName>test_disable_ver_11to17</testCaseName>
		<disables>
			<disable>
				<comment>disable version 11 to 17</comment>
				<version>[11, 17]</version>
			</disable>
		</disables>
		<command>echo "disable test for version 11 to 17"; \
	$(TEST_STATUS)</command>
	</test>

	<test>
		<testCaseName>test_disable_ver_8and17plus</testCaseName>
		<disables>
			<disable>
				<comment>disable version 8</comment>
				<version>8</version>
			</disable>
			<disable>
				<comment>disable version 11</comment>
				<version>17+</version>
			</disable>
		</disables>
		<command>echo "disable test for version 8 and 17+"; \
	$(TEST_STATUS)</command>
	</test>
</playlist>

=== adoptium/TKG/examples/platformRequirements/playlist.xml
<?xml version='1.0' encoding='UTF-8'?>
<!--
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
-->
<playlist xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../resources/playlist.xsd">
	<test>
		<testCaseName>test_arch_x86</testCaseName>
		<command>echo "test arch.x86"; \
	$(TEST_STATUS)</command>
		<platformRequirements>arch.x86</platformRequirements>
	</test>

	<test>
		<testCaseName>test_arch_x86_390</testCaseName>
		<command>echo "test arch.x86 or arch.390"; \
	$(TEST_STATUS)</command>
		<platformRequirementsList>
			<platformRequirements>arch.x86</platformRequirements>
			<platformRequirements>arch.390</platformRequirements>
		</platformRequirementsList>
	</test>
	<test>
		<testCaseName>test_arch_nonx86</testCaseName>
		<command>echo "test ^arch.x86"; \
	$(TEST_STATUS)</command>
		<platformRequirementsList>
			<platformRequirements>^arch.x86</platformRequirements>
		</platformRequirementsList>
	</test>

	<test>
		<testCaseName>test_bits_64</testCaseName>
		<command>echo "test bits.64"; \
	$(TEST_STATUS)</command>
		<platformRequirements>bits.64</platformRequirements>
	</test>

	<test>
		<testCaseName>test_os_osx</testCaseName>
		<command>echo "test os.osx"; \
	$(TEST_STATUS)</command>
		<platformRequirements>os.osx</platformRequirements>
	</test>

	<test>
		<testCaseName>test_osx_x86-64</testCaseName>
		<command>echo "test osx_x86-64"; \
	$(TEST_STATUS)</command>
		<platformRequirements>os.osx,bits.64,arch.x86</platformRequirements>
	</test>

	<test>
		<testCaseName>test_not_linux_arch_x86</testCaseName>
		<command>echo "test on none linux and on arch x86"; \
	$(TEST_STATUS)</command>
		<platformRequirements>^os.linux,arch.x86</platformRequirements>
	</test>

	<test>
		<testCaseName>test_osx_x86-64_win_x86_aix_ppc-64</testCaseName>
		<command>echo "test osx_x86-64 or win_x86 or aix_ppc-64"; \
	$(TEST_STATUS)</command>
		<platformRequirementsList>
			<platformRequirements>os.osx,bits.64,arch.x86</platformRequirements>
			<platformRequirements>os.win,bits.32,arch.x86</platformRequirements>
			<platformRequirements>os.aix,arch.ppc,bits.64</platformRequirements>
		</platformRequirementsList>
	</test>

	<test>
		<testCaseName>test_os_linux_ubuntu20plus</testCaseName>
		<command>echo "test os.linux.ubuntu.20+"; \
	$(TEST_STATUS)</command>
		<platformRequirements>os.linux.ubuntu.20+</platformRequirements>
	</test>

	<test>
		<testCaseName>test_os_linux_ubuntu22</testCaseName>
		<command>echo "test os.linux.ubuntu.22"; \
	$(TEST_STATUS)</command>
		<platformRequirements>os.linux.ubuntu.22</platformRequirements>
	</test>

	<test>
		<testCaseName>test_os_linux_ubuntu20plus_rhel8plus</testCaseName>
		<command>echo "test os.linux.ubuntu.20+ or os.linux.rhel.8+"; \
	$(TEST_STATUS)</command>
		<platformRequirementsList>
			<platformRequirements>os.linux.ubuntu.20+</platformRequirements>
			<platformRequirements>os.linux.rhel.8+</platformRequirements>
		</platformRequirementsList>
	</test>

	<test>
		<testCaseName>test_not_os_linux_ubuntu20plus</testCaseName>
		<command>echo "test on none os.linux.ubuntu.20+"; \
	$(TEST_STATUS)</command>
		<platformRequirements>^os.linux.ubuntu.20+</platformRequirements>
	</test>
	<test>
		<testCaseName>test_not_microarch_supported</testCaseName>
		<command>echo "test on none microarch.supported"; \
	$(TEST_STATUS)</command>
		<platformRequirements>^microarch.supported</platformRequirements>
	</test>
	<!-- Test for skylake microarchitecture -->
	<test>
		<testCaseName>test_microarch_skylake</testCaseName>
		<command>echo "test microarch.skylake"; \
		$(TEST_STATUS)</command>
		<platformRequirementsList>
			<platformRequirements>microarch.skylake</platformRequirements>
		</platformRequirementsList>
	</test>
	<!-- Test for z15+ microarchitecture -->
	<test>
		<testCaseName>test_microarch_z15plus</testCaseName>
		<command>echo "test microarch.z15+";
		$(TEST_STATUS)</command>
		<platformRequirementsList>
			<platformRequirements>microarch.z15+</platformRequirements>
		</platformRequirementsList>
	</test>
	<!-- Test for z15 microarchitecture -->
	<test>
		<testCaseName>test_microarch_z15</testCaseName>
		<command>echo "test microarch.z15"; \
		$(TEST_STATUS)</command>
		<platformRequirementsList>
			<platformRequirements>microarch.z15</platformRequirements>
		</platformRequirementsList>
	</test>
	<!-- Test for z14+ microarchitecture -->
	<test>
		<testCaseName>test_microarch_z14plus</testCaseName>
		<command>echo "test microarch.z14+"; \
		$(TEST_STATUS)</command>
		<platformRequirementsList>
			<platformRequirements>microarch.z14+</platformRequirements>
		</platformRequirementsList>
	</test>
	<!-- Test for z14 microarchitecture -->
	<test>
		<testCaseName>test_microarch_z14</testCaseName>
		<command>echo "test microarch.z14"; \
		$(TEST_STATUS)</command>
		<platformRequirementsList>
			<platformRequirements>microarch.z14</platformRequirements>
		</platformRequirementsList>
	</test>
	<!-- Test for z13+ microarchitecture -->
	<test>
		<testCaseName>test_microarch_z13plus</testCaseName>
		<command>echo "test microarch.z13+"; \
		$(TEST_STATUS)</command>
		<platformRequirementsList>
			<platformRequirements>microarch.z13+</platformRequirements>
		</platformRequirementsList>
	</test>
	<!-- Test for z13 microarchitecture -->
	<test>
		<testCaseName>test_microarch_z13</testCaseName>
		<command>echo "test microarch.z13"; \
		$(TEST_STATUS)</command>
		<platformRequirementsList>
			<platformRequirements>microarch.z13</platformRequirements>
		</platformRequirementsList>
	</test>

</playlist>
